"""empty message

Revision ID: de1be3b6fd7d
Revises: 
Create Date: 2024-12-15 16:48:09.584350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de1be3b6fd7d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "room",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bet_amount", sa.Integer(), nullable=False),
        sa.Column(
            "player_count",
            sa.Enum("TWO", "THREE", "FOUR", "FIVE", "SIX", name="playercount"),
            nullable=False,
        ),
        sa.Column(
            "deck_size",
            sa.Enum("SMALL", "MEDIUM", "FULL", name="decksize"),
            nullable=True,
        ),
        sa.Column("is_speed_mode", sa.Boolean(), nullable=False),
        sa.Column("is_transfer_allowed", sa.Boolean(), nullable=False),
        sa.Column("is_cheating_allowed", sa.Boolean(), nullable=False),
        sa.Column("is_draw_allowed", sa.Boolean(), nullable=False),
        sa.Column(
            "card_transfer_permission",
            sa.Enum("NEIGHBORS_ONLY", "ALL_PLAYERS", name="cardtransferpermission"),
            nullable=False,
        ),
        sa.Column("is_test", sa.Boolean(), nullable=True),
        sa.Column("is_private", sa.Boolean(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("trump_card", sa.String(), nullable=True),
        sa.Column(
            "balance_type",
            sa.Enum("BALANCE", "BONUS_BALANCE", "CLUB_BALANCE", name="wallettype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("WAITING", "READY", "IN_GAME", "FINISHED", name="roomstatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_room")),
    )
    op.create_index(
        op.f("ix_room_balance_type"), "room", ["balance_type"], unique=False
    )
    op.create_index(op.f("ix_room_created_at"), "room", ["created_at"], unique=False)
    op.create_index(op.f("ix_room_status"), "room", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_room_status"), table_name="room")
    op.drop_index(op.f("ix_room_created_at"), table_name="room")
    op.drop_index(op.f("ix_room_balance_type"), table_name="room")
    op.drop_table("room")
    # ### end Alembic commands ###
