"""empty message

Revision ID: 4be162dd4587
Revises: 
Create Date: 2024-11-14 21:00:57.084519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4be162dd4587"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "room",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bet_amount", sa.Integer(), nullable=False),
        sa.Column("player_count", sa.Integer(), nullable=False),
        sa.Column("deck_count", sa.Integer(), nullable=True),
        sa.Column("speed", sa.Boolean(), nullable=False),
        sa.Column("mod_transfer", sa.String(), nullable=False),
        sa.Column("mod_can_transfer", sa.String(), nullable=False),
        sa.Column("mod_deception", sa.String(), nullable=False),
        sa.Column("mod_game", sa.String(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column("is_test", sa.Boolean(), nullable=True),
        sa.Column("is_private", sa.Boolean(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("trump", sa.String(), nullable=True),
        sa.Column(
            "balance_type",
            sa.Enum(
                "BALANCE",
                "BONUS_BALANCE",
                "CLUB_BALANCE",
                name="wallettype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_room")),
    )
    op.create_index(
        op.f("ix_room_balance_type"), "room", ["balance_type"], unique=False
    )
    op.create_index(op.f("ix_room_created_at"), "room", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_room_created_at"), table_name="room")
    op.drop_index(op.f("ix_room_balance_type"), table_name="room")
    op.drop_table("room")
    # ### end Alembic commands ###
