"""empty message

Revision ID: df59ef3b6727
Revises: 4be162dd4587
Create Date: 2024-11-18 13:35:34.116345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "df59ef3b6727"
down_revision: Union[str, None] = "4be162dd4587"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "room",
        sa.Column("knokout", sa.Boolean(), nullable=False, server_default="False"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("room", "knokout")
    # ### end Alembic commands ###
